{
    "totalCount": 1,
    "data": [{
    "title": "活动详情",
    "visit_num": 143,
    "value": 143,
    "leave_rate": "78.32%",
    "page_visit_num": 1,
    "retention_num": 31,
    "i": 0
}, {
    "title": "活动",
    "visit_num": 15,
    "value": 15,
    "leave_rate": "80.00%",
    "page_visit_num": 2,
    "retention_num": 3,
    "i": 1
}, {
    "title": "兴趣",
    "visit_num": 4,
    "value": 4,
    "leave_rate": "0.00%",
    "page_visit_num": 2,
    "retention_num": 4,
    "i": 2
}, {
    "title": "活动描述",
    "visit_num": 3,
    "value": 3,
    "leave_rate": "0.00%",
    "page_visit_num": 2,
    "retention_num": 3,
    "i": 3
}, {
    "title": "演出",
    "visit_num": 3,
    "value": 3,
    "leave_rate": "0.00%",
    "page_visit_num": 2,
    "retention_num": 3,
    "i": 4
}, {
    "title": "娱乐",
    "visit_num": 2,
    "value": 2,
    "leave_rate": "0.00%",
    "page_visit_num": 2,
    "retention_num": 2,
    "i": 5
}, {
    "title": "查看报名",
    "visit_num": 2,
    "value": 2,
    "leave_rate": "100.00%",
    "page_visit_num": 2,
    "retention_num": 0,
    "i": 6
}, {
    "title": "会议",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "0.00%",
    "page_visit_num": 2,
    "retention_num": 1,
    "i": 7
}, {
    "title": "活动已删除",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "100.00%",
    "page_visit_num": 2,
    "retention_num": 0,
    "i": 8
}, {
    "title": "活动",
    "visit_num": 8,
    "value": 8,
    "leave_rate": "37.50%",
    "page_visit_num": 3,
    "retention_num": 5,
    "i": 9
}, {
    "title": "兴趣",
    "visit_num": 2,
    "value": 2,
    "leave_rate": "0.00%",
    "page_visit_num": 3,
    "retention_num": 2,
    "i": 10
}, {
    "title": "发布活动",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "100.00%",
    "page_visit_num": 3,
    "retention_num": 0,
    "i": 11
}, {
    "title": "娱乐",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "0.00%",
    "page_visit_num": 3,
    "retention_num": 1,
    "i": 12
}, {
    "title": "展览",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "0.00%",
    "page_visit_num": 3,
    "retention_num": 1,
    "i": 13
}, {
    "title": "户外",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "0.00%",
    "page_visit_num": 3,
    "retention_num": 1,
    "i": 14
}, {
    "title": "确认报名",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "100.00%",
    "page_visit_num": 3,
    "retention_num": 0,
    "i": 15
}, {
    "title": "运动",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "100.00%",
    "page_visit_num": 3,
    "retention_num": 0,
    "i": 16
}, {
    "title": "发布活动",
    "visit_num": 3,
    "value": 3,
    "leave_rate": "100.00%",
    "page_visit_num": 4,
    "retention_num": 0,
    "i": 17
}, {
    "title": "活动",
    "visit_num": 2,
    "value": 2,
    "leave_rate": "100.00%",
    "page_visit_num": 4,
    "retention_num": 0,
    "i": 18
}, {
    "title": "会议",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "0.00%",
    "page_visit_num": 4,
    "retention_num": 1,
    "i": 19
}, {
    "title": "娱乐",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "0.00%",
    "page_visit_num": 4,
    "retention_num": 1,
    "i": 20
}, {
    "title": "户外",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "0.00%",
    "page_visit_num": 4,
    "retention_num": 1,
    "i": 21
}, {
    "title": "编辑活动",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "0.00%",
    "page_visit_num": 4,
    "retention_num": 1,
    "i": 22
}, {
    "title": "运动",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "100.00%",
    "page_visit_num": 4,
    "retention_num": 0,
    "i": 23
}, {
    "title": "活动",
    "visit_num": 2,
    "value": 2,
    "leave_rate": "50.00%",
    "page_visit_num": 5,
    "retention_num": 1,
    "i": 24
}, {
    "title": "发布活动",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "100.00%",
    "page_visit_num": 5,
    "retention_num": 0,
    "i": 25
}, {
    "title": "娱乐",
    "visit_num": 1,
    "value": 1,
    "leave_rate": "0.00%",
    "page_visit_num": 5,
    "retention_num": 1,
    "i": 26
}]
}